### PR TITLE
Remix lib ASTwalker typescript transformation

### PR DESCRIPTION
**Pull request by 0mkara**
- [x] astwalker transformation into typescript
- [x] add Eventemitter support
- [x] maintain backward compatiable callback support
- [x] pass old tests

### CODE REVIEW

**Comment by Ayanrocks** [comment]
@0mkara Completed all tasks

**Comment by Ayanrocks** [comment]
@0mkara  Done

**Comment by 0mkara** [comment]
@Ayanrocks we are having an error on `resources/ast.ts`.

```
Type '{ "legacyAST": { "children": { "attributes": { "fullyImplemented": boolean; "isLibrary": boolean; "linearizedBaseContracts": number[]; "name": string; }; "children": ({ "attributes": { "name": string; "type": string; }; "children": { ...; }[]; "id": number; "name": string; "src": string; } | { ...; })[]; "id": numbe...' is missing the following properties from type 'AstNode': id, nodeType, srcts(2739)
```
Kindly check.

**Comment by Ayanrocks** [comment]
> @Ayanrocks we are having an error on `resources/ast.ts`.
> 
> ```
> Type '{ "legacyAST": { "children": { "attributes": { "fullyImplemented": boolean; "isLibrary": boolean; "linearizedBaseContracts": number[]; "name": string; }; "children": ({ "attributes": { "name": string; "type": string; }; "children": { ...; }[]; "id": number; "name": string; "src": string; } | { ...; })[]; "id": numbe...' is missing the following properties from type 'AstNode': id, nodeType, srcts(2739)
> ```
> Kindly check.

Tests are all passing. How this error happened? What data you passed to astwalker?

**Pull request closed without merging**
